operationCenter:
  # -- http or https
  protocol: "https"
  # -- DNS zone (Eg: Route 53 in Hosted Zone in AWS)
  hostname: "example.com"
  # -- Subdomain prefix used for all CloudBees CI applications (Operation Center and Controllers)
  subdomain: "ci"
  ingress:
    # -- alb or nlb
    class: nlb
  casc:
    # -- Location of CloudBees Bundle Storage for Controller
    controllerBundleStorageSCM: "https://github.com/cbci-playground/cb-casc-controllers.git"
  credentials:
    # -- Github Secret pair
    github:
      # -- Github Secret for token
      token: "ghp_xxxxExampleToken"
      # -- Github Secret for user
      user: "gh_ExampleUser"
    jenkins:
      # -- Jenkins password
      pass: "thisIsSecret"
controllers:
  # -- Enable Limit Range and Resource Quoatas
  policies: false
  loadTest:
    # -- Number of Load Controllers for Performance Testing
    controllers: 1
agents:
  # -- Agents Namespace name
  namespace: "cbci-agents"
  # -- Enable Limit Range and Resource Quoatas
  policies: false
  cache:
    # -- Cache for builds artifacts
    enable: false
    # -- Storage Class Name for PVC. Empty string will take the default one
    storageClassName: ""
