grafana:
  dashboard:
    # -- Configmap for defining CloudBees CI Controllers
    cbciControllersConfigmap: true
controllers:
  loadTest:
    prefix: load-boy
    # -- Number of Load Controllers for Performance Testing
    controllers: 2
