apiVersion: v1
kind: ConfigMap
metadata:
  name: oc-casc-bundle
  annotations:
    docs: "https://docs.cloudbees.com/docs/cloudbees-ci/latest/casc-oc/configure-oc-modern"
data:
  bundle.yaml: |-
{{ .Files.Get "casc/oc/modern/bundle.yaml" | indent 4 }}
  main.yaml: |-
{{ .Files.Get "casc/oc/modern/main.yaml" | indent 4 }}
  location.yaml: |-
    unclassified:
      location:
{{- if eq .Values.operationCenter.ingress.class "alb" }}
          url: {{ printf "%s://cjoc.%s" .Values.operationCenter.protocol .Values.operationCenter.hostname }}
{{- else }}
          url: {{ printf "%s://%s.%s/cjoc/" .Values.operationCenter.protocol .Values.operationCenter.subdomain .Values.operationCenter.hostname }}
{{- end }}
  controllerBundleStorageSCM.yaml: |-
    unclassified:
      # Best-Practice: Use SCM for Managed Master Casc Bundles
      # https://docs.cloudbees.com/docs/cloudbees-ci/2.332.3.4/casc-controller/add-bundle#_adding_casc_bundles_from_an_scm_tool
      bundleStorageService:
        activated: true
        activeBundle:
          name: "casc-store"
          retriever:
            SCM:
              scmSource:
                git:
                  credentialsId: "GH-token"
                  remote: {{ .Values.operationCenter.casc.controllerBundleStorageSCM | quote }}
                  traits:
                    - "gitBranchDiscovery"
  security.yaml: |-
{{ .Files.Get "casc/oc/modern/security.yaml" | indent 4 }}
  plugins.yaml: |-
{{ .Files.Get "casc/oc/modern/plugins.yaml" | indent 4 }}
  plugin-catalog.yaml: |-
{{ .Files.Get "casc/oc/modern/plugin-catalog.yaml" | indent 4 }}
  items-folder-admin.yaml: |-
{{ .Files.Get "casc/oc/modern/items-folder-admin.yaml" | indent 4 }}
  items-root.yaml: |-
{{ .Files.Get "casc/oc/modern/items-root.yaml" | indent 4 }}
  items-load-controllers.yaml: |-
    removeStrategy:
      items: NONE
      rbac: SYNC
{{- if gt (int .Values.controllers.loadTest.controllers) 0 }}
    items:
{{- range (untilStep 0 (int .Values.controllers.loadTest.controllers) 1) }}
    - kind: managedController
      name: load-boy{{ . }}
      properties:
      - configurationAsCode:
          bundle: "modern.load-boy"
      configuration:
        kubernetes:
          domain: load-boy{{ . }}
          memory: 3500
          cpus: 2.0
          disk: 30
{{- end }}
{{- else }}
    items: []
{{- end }}
